/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.72
 * Generated at: 2017-01-15 09:30:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ch02_002dbasicObject;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class makeRequestParameter_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<form action=\"viewParameter_enumer.jsp\" method=\"post\">\r\n");
      out.write("\t\t이름: <input type=\"text\" name=\"name\" size=\"10\"><br>\r\n");
      out.write("\t\t주소: <input type=\"text\" name=\"address\" size=\"30\"><br>\r\n");
      out.write("\t\t좋아하는 영화: \r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"movie\" value=\"interstella\" checked=\"checked\">인터스텔라\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"movie\" value=\"inception\">인셉션\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"movie\" value=\"martion\">마션\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"movie\" value=\"gravity\">그래비티\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"movie\" value=\"core\">코어\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t전공: \r\n");
      out.write("\t\t<input type=\"radio\" name=\"major\" value=\"management\">경영\r\n");
      out.write("\t\t<input type=\"radio\" name=\"major\" value=\"machine\">기계공학\r\n");
      out.write("\t\t<input type=\"radio\" name=\"major\" value=\"math\">수학\r\n");
      out.write("\t\t<input type=\"radio\" name=\"major\" value=\"biology\">생명화학\r\n");
      out.write("\t\t<input type=\"radio\" name=\"major\" value=\"society\" checked=\"checked\">사회학\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t취미:\r\n");
      out.write("\t\t<select name=\"hobby\">\r\n");
      out.write("\t\t\t<option value=\"basketball\">농구</option>\r\n");
      out.write("\t\t\t<option value=\"ballyball\">배구</option>\r\n");
      out.write("\t\t\t<option value=\"baseball\">야구</option>\r\n");
      out.write("\t\t\t<option value=\"soccer\">축구</option>\r\n");
      out.write("\t\t\t<option value=\"reading\">독서</option>\r\n");
      out.write("\t\t\t<option value=\"fishing\" selected=\"selected\">낚시</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"전송\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
